//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anastasia423WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Master
    {
        public int ID { get; set; }
        public int MasterID { get; set; }
        public int ServiceID { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual User User { get; set; }
    }
}
